language: php

php:
  - 7.0

before_script:
  - mkdir -p ~/.composer
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer self-update
  - composer update --prefer-source --dev --no-interaction

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit tests